# Generated by Django 4.2.9 on 2025-09-05 03:50

import LCD.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotline', models.CharField(max_length=50)),
                ('isadmin', models.BooleanField(default=False)),
                ('adddate', models.DateTimeField(auto_now_add=True)),
                ('lastupdatedate', models.DateTimeField(auto_now=True)),
                ('lastupdateuserid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_accounts', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictureName', models.ImageField(upload_to=LCD.models.upload_to)),
                ('isDeleted', models.BooleanField(default=False)),
                ('addDate', models.DateTimeField(auto_now_add=True)),
                ('deletedDate', models.DateTimeField(blank=True, null=True)),
                ('lastUpdateDate', models.DateTimeField(auto_now=True)),
                ('lastupdateuserid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plate', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True, max_length=50, null=True)),
                ('adddate', models.DateTimeField(auto_now_add=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('deletedate', models.DateTimeField(blank=True, null=True)),
                ('lastupdatedate', models.DateTimeField(auto_now=True)),
                ('KHDV', models.CharField(blank=True, max_length=50, null=True)),
                ('CVDV', models.CharField(blank=True, max_length=50, null=True)),
                ('lastupdateuserid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
