# Generated by Django 4.2.9 on 2025-09-05 04:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LCD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='adddate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
