# Generated by Django 4.2.9 on 2025-09-05 04:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LCD', '0002_alter_customer_adddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='addDate',
        ),
        migrations.AddField(
            model_name='pictures',
            name='adddate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
