# Generated by Django 4.2.9 on 2025-09-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCD', '0003_remove_pictures_adddate_pictures_adddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='store',
            field=models.CharField(choices=[('HDN', 'Honda Ô tô Đà Nẵng'), ('HQN', 'Honda Ô tô Quảng Nam'), ('TTQN', 'Toyota Quảng Ngãi'), ('TLQN', 'Toyota Trang Lê Quảng Nam')], default='', max_length=10),
        ),
    ]
